nav:
  Home: /
  Writing: /archives/
  E3news: http://e3news.herokuapp.com/
  Projects: http://github.com/leyluiaa

projects_url: http://github.com/leyluiaa

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/leyluiaa
        twitter: https://twitter.com/leyluiaa
    post_count: 5
    highlight: rainbow

# RSS
rss: atom.xml

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-90597082-1

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
